/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

import inheritance.restaurant.*;

public class App {


    public static void main(String[] args) {


        Restaurant myTestR = new Restaurant("Chipotle");
        System.out.println(myTestR.toString());

        Restaurant myOtherTestR = new Restaurant("Dominoes", "Pizza");

        Review jReview = new Review(new StringBuilder("Pizza was trash I cannot believe that I did that"),"Juan", 1);
        myOtherTestR.addReview(jReview);
        System.out.println(myOtherTestR.toString());

        Review kReview = new Review(new StringBuilder("awful just awful"),"kimmy", 4);
        Shop appleStore = new Shop("Apple Store Tacoma");
        appleStore.addReview(kReview);

        System.out.println(appleStore.toString());

        Theater amc = new Theater("Tacoma");
        amc.setEstablishmentName("AMC");
        MovieReview aReview = new MovieReview("Batman","Alex", 2, new StringBuilder("This movie was not good at all, do not reccomend"));
        amc.addReview(aReview);

        System.out.println(amc.toString());


    }
}
